exports.CAT_BREEDS = [
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "Chartreux",
  "Chausie",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Devon Rex",
  "Egyptian Mau",
  "European Burmese",
  "Exotic Shorthair",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Khao Manee",
  "Korat",
  "LaPerm",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental Longhair",
  "Persian",
  "Pixiebob",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Serengeti",
  "Oriental Shorthair",
  "Siamese",
  "Siberian",
  "Singapura",
  "Somali",
  "Sphynx",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
];

exports.DOG_BREEDS = [
  "Labrador Retriever",
  "French Bulldog",
  "German Shepherd",
  "Golden Retriever",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "German Shorthaired Pointer",
  "Dachshund",
  "Pembroke Welsh Corgi",
  "Australian Shepherd",
  "Yorkshire Terrier",
  "Boxer",
  "Great Dane",
  "Siberian Husky",
  "Cavalier King Charles Spaniel",
  "Doberman Pinscher",
  "Miniature Schnauzer",
  "Shih Tzu",
  "Boston Terrier",
  "Bernese Mountain Dog",
  "Pomeranian",
  "Havanese",
  "Cane Corso",
  "English Springer Spaniel",
  "Shetland Sheepdog",
  "Brittany",
  "Pug",
  "Cocker Spaniel",
  "Miniature American Shepherd",
  "Border Collie",
  "Mastiff",
  "Chihuahua",
  "Vizsla",
  "Basset Hound",
  "Belgian Malinoi",
  "Maltese",
  "Weimaraner",
  "Collie",
  "Newfoundland",
  "Rhodesian Ridgeback",
  "Shiba Inu",
  "West Highland White Terrier",
  "Bichons Frise",
  "Bloodhound",
  "English Cocker Spaniel",
  "Akita",
  "Portuguese Water Dog",
  "Chesapeake Bay Retriever",
  "Dalmatian",
  "St. Bernard",
  "Papillon",
  "Australian Cattle Dog",
  "Bullmastiff",
  "Samoyed",
  "Scottish Terrier",
  "Soft Coated Wheaten Terrier",
  "Whippet",
  "German Wirehaired Pointer",
  "Chinese Shar-Pei",
  "Airedale Terrier",
  "Wirehaired Pointing Griffon",
  "Bull Terrier",
  "Alaskan Malamute",
  "Cardigan Welsh Corgi",
  "Giant Schnauzer",
  "Old English Sheepdog",
  "Italian Greyhound",
  "Great Pyrenees",
  "Dogues de Bordeaux",
  "Russell Terrier",
  "Cairn Terrier",
  "Irish Wolfhound",
  "Irish Setter",
  "Greater Swiss Mountain Dog",
  "Miniature Pinscher",
  "Lhasa Apso",
  "Chinese Crested",
  "Coton de Tulear",
  "Staffordshire Bull Terrier",
  "American Staffordshire Terrier",
  "Rat Terrier",
  "Chow Chow",
  "Anatolian Shepherd Dog",
  "Basenji",
  "Boykin Spaniel",
  "Lagotti Romagnoli",
  "Brussels Griffon",
  "Nova Scotia Duck Tolling Retriever",
  "Norwegian Elkhound",
  "Standard Schnauzer",
  "Dogo Argentino",
  "Bouviers des Flandres",
  "Pekingese",
  "Keeshonden",
  "Border Terrier",
  "Leonberger",
  "Tibetan Terrier",
  "Neapolitan Mastiff",
  "English Setter",
  "Flat-Coated Retriever",
  "Borzois",
  "Wire Fox Terrier",
  "Miniature Bull Terrier",
  "Belgian Tervuren",
  "Gordon Setter",
  "Silky Terrier",
  "Norwich Terrier",
  "Spinoni Italiani",
  "Japanese Chin",
  "Welsh Terrier",
  "Toy Fox Terrier",
  "Schipperke",
  "Parson Russell Terrier",
  "Pointer",
  "Belgian Sheepdog",
  "Tibetan Spaniel",
  "American Eskimo Dog",
  "Irish Terrier",
  "Beauceron",
  "Afghan Hound",
  "Boerboel",
  "Smooth Fox Terrier",
  "Bearded Collie",
  "Black Russian Terrier",
  "Black and Tan Coonhound",
  "Welsh Springer Spaniel",
  "American Hairless Terrier",
  "Norfolk Terrier",
  "Xoloitzcuintli",
  "Manchester Terrier",
  "Kerry Blue Terrier",
  "Australian Terrier",
  "Clumber Spaniel",
  "Lakeland Terrier",
  "Bluetick Coonhound",
  "English Toy Spaniel",
  "German Pinscher",
  "Tibetan Mastiff",
  "Bedlington Terrier",
  "Greyhound",
  "Pulik",
  "Saluki",
  "Barbet",
  "Redbone Coonhound",
  "Swedish Vallhund",
  "Sealyham Terrier",
  "Spanish Water Dog",
  "Briard",
  "Berger Picard",
  "Entlebucher Mountain Dog",
  "Treeing Walker Coonhound",
  "Icelandic Sheepdog",
  "Wirehaired Vizsla",
  "Pumik",
  "Portuguese Podengo Pequeno",
  "American Water Spaniel",
  "Curly-Coated Retriever",
  "Field Spaniel",
  "Lowchen",
  "Nederlandse Kooikerhondje",
  "Affenpinscher",
  "Petits Bassets Griffons Vendeen",
  "Finnish Lapphund",
  "Scottish Deerhound",
  "Plott Hound",
  "Norwegian Buhund",
  "Glen of Imaal Terrier",
  "Irish Red and White Setter",
  "Ibizan Hound",
  "Sussex Spaniel",
  "Bergamasco Sheepdog",
  "Irish Water Spaniel",
  "Polish Lowland Sheepdog",
  "Otterhound",
  "Kuvaszok",
  "Komondorok",
  "Cirnechi dell’Etna",
  "Pharaoh Hound",
  "Dandie Dinmont Terrier",
  "Pyrenean Shepherd",
  "Skye Terrier",
  "Canaan Dog",
  "American English Coonhound",
  "Chinook",
  "Finnish Spitz",
  "Grand Basset Griffon Vendeen",
  "Sloughi",
  "Harrier",
  "Cesky Terrier",
  "American Foxhound",
  "Azawakh",
  "English Foxhound",
  "Norwegian Lundehund",
];

exports.OTHER_BREEDS = [
  "Goat",
  "Chicken",
  "Parakeet",
  "Parrot",
  "Lizard",
  "Chameleon",
  "Pot Belly Pig",
  "Finch",
  "Ferret",
  "Rat",
  "Mouse",
  "Hamster",
  "Gerbil",
  "Tropical Fish",
  "Iguana",
  "Gold Fish",
  "Beta",
  "Koi",
  "Snake",
  "Guinea Pig",
  "Hedgehog",
  "Chinchilla",
  "Hermit Crab",
  "Rabbit",
];
